---
- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/users/"
  controller: "UserController::getAction"
  methods: [GET, POST]

- url: "/locations/[i:locationId]/counts/[i:countId]/instances/[i:instanceId]"
  controller: "\\v1\\Controller\\Collection\\CountsController"
  methods: [GET, POST, DELETE]
...
